# Generated by Django 2.0 on 2018-10-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighFrequencyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True, verbose_name='单词')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '高频单词',
                'verbose_name_plural': '高频单词',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_file', models.FileField(upload_to='export/', verbose_name='分析文件')),
                ('unknown_file', models.FileField(upload_to='export/', verbose_name='未知单词文件')),
                ('finished', models.BooleanField(default=False)),
                ('note', models.CharField(max_length=1024)),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '导入记录',
                'verbose_name_plural': '导入记录',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '导入系列',
                'verbose_name_plural': '导入系列',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='ImportSessionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='session/')),
                ('used', models.BooleanField(default=False)),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_files', to='app.ImportSession')),
            ],
            options={
                'verbose_name': '导入文件',
                'verbose_name_plural': '导入文件',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='QueryDictFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdx_file', models.FileField(upload_to='dict/', verbose_name='字典文件')),
                ('mdd_file', models.FileField(upload_to='dict/', verbose_name='数据文件')),
                ('mdx_md5', models.CharField(max_length=64, verbose_name='md5')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '字典文件',
                'verbose_name_plural': '字典文件',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='QueryTranslateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='翻译信息')),
                ('target', models.CharField(blank=True, max_length=128, null=True, verbose_name='句子信息')),
                ('uk_phonetic', models.CharField(blank=True, max_length=128, null=True, verbose_name='英式')),
                ('us_phonetic', models.CharField(blank=True, max_length=128, null=True, verbose_name='美式')),
                ('translate', models.TextField(blank=True, null=True, verbose_name='翻译信息')),
                ('frequency', models.IntegerField(verbose_name='查询次数')),
                ('source_from', models.CharField(default='inner', max_length=128, verbose_name='查询来源')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('session_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ImportSessionFile')),
            ],
            options={
                'verbose_name': '查询记录',
                'verbose_name_plural': '查询记录',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='QueryWordTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='标签名称')),
                ('style', models.TextField(verbose_name='标签样式')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='标签颜色')),
                ('font_color', models.CharField(default='#000000', max_length=7, verbose_name='字体颜色')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单词标签',
                'verbose_name_plural': '单词标签',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='SentenceKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, verbose_name='词汇')),
                ('info', models.CharField(max_length=128, verbose_name='解释')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('query_translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_keyword', to='app.QueryTranslateRecord', verbose_name='查询信息')),
            ],
            options={
                'verbose_name': '关联词',
                'verbose_name_plural': '关联词',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='SentenceRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128, verbose_name='翻译信息')),
                ('target', models.CharField(max_length=128, verbose_name='句子信息')),
                ('resource', models.CharField(max_length=128, verbose_name='来源')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('query_translate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_relative', to='app.QueryTranslateRecord', verbose_name='查询信息')),
            ],
            options={
                'verbose_name': '关联句子',
                'verbose_name_plural': '关联句子',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='SessionSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('sentence', models.CharField(max_length=1024)),
                ('sentence_prototype', models.CharField(max_length=1024)),
                ('time', models.CharField(blank=True, max_length=16, null=True)),
                ('note', models.CharField(blank=True, max_length=1024, null=True)),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sentences', to='app.ImportSession')),
                ('session_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_file_sentences', to='app.ImportSessionFile')),
            ],
            options={
                'verbose_name': '材料句子',
                'verbose_name_plural': '材料句子',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='SessionWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('frequency', models.IntegerField(default=0)),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_words', to='app.ImportSession')),
            ],
            options={
                'verbose_name': '材料单词',
                'verbose_name_plural': '材料单词',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='UserQueryDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_name', models.CharField(max_length=64, verbose_name='字典名称')),
                ('position', models.IntegerField(verbose_name='排序位置')),
                ('up', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('dict_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QueryDictFile', verbose_name='字典文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '查询字典',
                'verbose_name_plural': '查询字典',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True, verbose_name='单词')),
                ('query_count', models.IntegerField(default=0, verbose_name='查询次数')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户词表',
                'verbose_name_plural': '用户词表',
                'ordering': ['ct'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True, verbose_name='单词')),
                ('uk_sound', models.FileField(blank=True, null=True, upload_to='vocabulary/sound/', verbose_name='音式发音')),
                ('us_sound', models.FileField(blank=True, null=True, upload_to='vocabulary/sound/', verbose_name='美式发音')),
                ('uk_phonetic', models.CharField(blank=True, max_length=32, null=True, verbose_name='英式音标')),
                ('us_phonetic', models.CharField(blank=True, max_length=32, null=True, verbose_name='美式音标')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vocabulary/picture/', verbose_name='联想图片')),
                ('star', models.CharField(max_length=12, verbose_name='单词星级')),
                ('high_frequency', models.BooleanField(default=False, verbose_name='高频词')),
                ('en_desc', models.TextField(verbose_name='英文解释')),
                ('cn_desc', models.TextField(verbose_name='中文解释')),
                ('query_count', models.IntegerField(default=0, verbose_name='查询次数')),
                ('ct', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '常用单词',
                'verbose_name_plural': '常用单词',
                'ordering': ['ct'],
            },
        ),
        migrations.AddField(
            model_name='uservocabulary',
            name='word_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vocabulary', to='app.Vocabulary'),
        ),
        migrations.AddField(
            model_name='querytranslaterecord',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_query_translate', to='app.QueryWordTag'),
        ),
        migrations.AddField(
            model_name='querytranslaterecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
