# Generated by Django 2.0 on 2018-11-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181025_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquerydict',
            options={'ordering': ['ct'], 'verbose_name': '查询字典', 'verbose_name_plural': '查询字典'},
        ),
    ]
